apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Homelab developer portal
  links:
    - url: http://192.168.0.108:30900
      title: Backstage UI
  annotations:
    argocd/app-name: backstage
    github.com/project-slug: Blacklotus89898/Homelab
    backstage.io/kubernetes-namespace: backstage
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=backstage'
spec:
  type: website
  lifecycle: production
  owner: user:blacklotus89898
  system: homelab
