apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: git@github.com:Blacklotus89898/Homelab.git
    targetRevision: HEAD
    path: infrastructure/jenkins
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
