fullnameOverride: sealed-secrets-controller

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi

# Key rotation: default is 30d key renewal, 365d expiry. Fine for homelab.
# keyrenewperiod: "720h"
