apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: default
  labels:
    app: linkding
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: linkding
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
        - name: linkding
          image: sissbruecker/linkding:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          env:
            - name: LD_DISABLE_BACKGROUND_TASKS
              value: "False"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-pvc
