apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: homelab-root
  description: All Homelab catalog entities
spec:
  targets:
    - ./homelab-system.yaml
    - ./users.yaml
    - ./apis.yaml
    - ./components/argocd.yaml
    - ./components/openobserve.yaml
    - ./components/authentik.yaml
    - ./components/linkding.yaml
    - ./components/paperless.yaml
    - ./components/audiobookshelf.yaml
    - ./components/kavita.yaml
    - ./components/jenkins.yaml
