apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: homelab-root
  description: All Homelab catalog entities
spec:
  targets:
    - ./homelab-system.yaml
    - ./users.yaml
    - ./components/*.yaml
    - https://raw.githubusercontent.com/Blacklotus89898/Homelab/main/templates/homelab-service/template.yaml
