replicaCount:
  ingester: 1
  querier: 1
  router: 1
  alertmanager: 1
  alertquerier: 0
  compactor: 1
  reportserver: 0
  o2ai: 0

# TODO: move to SealedSecret
auth:
  ZO_ROOT_USER_EMAIL: "admin@homelab.local"
  ZO_ROOT_USER_PASSWORD: "CHANGE_ME"
  ZO_ROOT_USER_TOKEN: ""
  ZO_S3_ACCESS_KEY: ""
  ZO_S3_SECRET_KEY: ""
  ZO_META_POSTGRES_DSN: ""
  ZO_META_POSTGRES_RO_DSN: ""
  ZO_TRACING_HEADER_KEY: "Authorization"
  ZO_TRACING_HEADER_VALUE: ""
  ZO_RUM_CLIENT_TOKEN: ""
  ZO_REPORT_USER_EMAIL: ""
  ZO_REPORT_USER_PASSWORD: ""
  ZO_SMTP_USER_NAME: ""
  ZO_SMTP_PASSWORD: ""
  O2_MCP_USERNAME: ""
  O2_MCP_PASSWORD: ""

config:
  ZO_META_STORE: "sqlite"
  ZO_META_CONNECTION_POOL_MIN_SIZE: "0"
  ZO_META_CONNECTION_POOL_MAX_SIZE: "0"

postgres:
  enabled: false

alertmanager:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: local-path
    accessModes:
      - ReadWriteOnce

compactor:
  persistence:
    enabled: false

service:
  type: ClusterIP
  port: 5080
  grpcPort: 5081

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    memory: 2Gi
