---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAQrxfpsBlh+N/ug1XkQWjdLtMZS35pBLFs4zTCsdf7ox4QPr1grz/zkcq8sXb+leixkcdLPp8Kyk26g2GM0GTxDlorqDHdfTKEfSZcXcSj6zA6M5fwdqU4rXpSk9/4DAV2E50jTfxn6qSjn0ZhqXjYznII2PIiU8Xskn3y+AdyfqSpszWRPg4LXD+wHhefb7xYnK0GJT/+DPOs6cG6M6WFwipJd/7B4X3z7Me+bC7qeYjK7KpBsh9A7yKjrQaIhR71WWnxgrQ130/J+B4RACphBdTUKgdZU29kbMOKhO2ECvGci560JhRrafzVyhiHzd28u0VT4G28KYntDcDIywz6wwS1/Yfkr+yVWNleQO5g8w27RWv6hmFoNKNsu6I0nznaNI7R8V6H4tZVVhKBww3I5UibBc2YADz9QgQ5hcsq1s3Rk382Oucd6aePHGLcBXQLffbdGngG7feqkt21wkMniaLU5vA78hxY1PZcqYX1UQL4ikI1NnZRSAVt+eZawnJovUNbZQe0vFuszO6zdem04D7YQwMCFCBssuHAsmyB0fM9b5M7Oh3MViRxkKwdyQosv72tznqe5hmX/inSvSLzvvTcrR5niVt6xWuvsjEno/r8b12Gf5Gn77d/RD1GrLkxDUnYC5RaXczRELSfOzsVvfz+o0LrRnzvUn0nLWJbCC2daHvp7bE3Fw7P5/3D/AVgxr3CQo+HoAQmitg4g/P+qqhuNl4oPvQ=
    admin-user: AgAYKOl3UoGOYZe5PkBhw3PNefQkkuVa2zHC4E9d8fFObYEB0fx5JTGRvfzgL/ampPmDRLSXhjP3aNwP78ODquTBEz2qkuTZgMBliPJEoiLZIpAvlCyR+0yXW1rlBqzCnWnJEY4Bb4VB9XoRVSIQ2XfGpLQ3AzwpKUcdZrx6mOBP4NxeZUX6fAZ9X7OJNEvt0789it8MRabSb7wf5hW+KKigxOoTD4DXx0sumGDPwaIG+slv8DS68SFktzXXt1wHYA5zMdNvB/+Qw0p7hCiFKr/YIW0WAk4kSV+Ww2LEx9Ud82iYuI9DVHQMoFJaKMnni7J0HVUvGFdnhTPwmna2FPLtbB8V0pqlfR17fyUQi1TDWTadq0OCrARIaihFudh0eI12hpskUAqLlWMS3uXQQICMBHi7RaoI8CL3nOOVuhcHZqhuZDFvF0vhrM4YvIEbRkWmqJfBqf77rCSooT2JfOkgibdkHcmc89cRP8FCNFb9RoQjaABm2HJyF7HtM0OCgg/HLqWaCURmj/TvJt+jTRJvxFQ3kNPfd0SZB5xU0/tykIrRE4VUD7BrrX6s0V2Dpot/CpIhLWM8FebKa72VYhGs3P8W7Fv2YTysfo81SznrUpugPkE7sFkxJ2SuhpRWEXg3oaG+KBK7ZN56BjxNq+DRrw9+OBhx03Y12GexTWmTgvvzkPYz1zwV6eSEBoQJM4kLxb7f6A==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
