apiVersion: v1
kind: Service
metadata:
  name: petal
  namespace: petal
  labels:
    app: petal
spec:
  type: NodePort
  selector:
    app: petal
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30990
