# Sealed by kubeseal 0.40.0 from the live deployment env on 2026-09-30
# (values piped kubectl->kubeseal, never displayed). Scope: strict (name+ns).
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-credentials
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAwL1lHlndQZg1fxcIXnogSKWTEh1uV9AJijA4Z6doF8Hvbo12ZknJu/T1SqP3Ba+K0by9SIXOlqMnzSUJ4GXn/YSQoX/4P3qt7/vKMwG6fW62EfgzZ35LhWI8YGS4+s3/BSbp3wwo8PTd6xHDuzxeVnwGeLvjb3pPmCLY6zSdLG0XnuhnPK1dT9bn9FWDn9aL9QXV9mQi7JgxJxnGPNt32Di/3gWQW80swz7knmrLYTyS/YE55UOQs5iQ7haxkYc88/SeLum9iJAs44LgX77EnJbvDZxvI+l8YKaUaQW2frNgB263WDvxF7fhoZkAtdy2421+NsGUow+GJCwayvFFp5P3XtBeGIOKT+Pc/EoE6LDxu4O1FvIFEUZgM64cz0/l7sVPX2YMdTwA6b2Ld+RmaGPgLDrgTqMg31bJun3fnU8TXIpvIYRHq/kpyglf0cO12FItJKr8Eww1BR4pOVr/D17MyG80jZt+gNxjKmzFrL4lTwCUoSCE/fOspgONUFo9RzJzJbkA+V4Mm9QXLR6MnxZjIiCUBWo/0YIz1enOb5om7OlRRhhUtS7+Nu5R1fF1ENv5z2Gleon1QJSWVvueswe5u6tYf1KABnnJcVHSEfFt+OcyqLFMi9DkBJ9DFzJZKSYMtFNKeiED0AslX9ypsmBiBpDy3qL65aYnugR2Vz3CDCbnkcjiO7lWlF5UllZnNu/ey7JYKjm3xf1QlJu8OuaTRpVI=
    SECRET_KEY: AgAQtTUldDJQO6jAztwbZYczsrYu7/RsZSteyp2c+tCP+bxfLDciUlPMCZn3tZTKNORZ0k61trru8Gki6oGfrpKVTsCNE1CNcLE+Rfs0Fe+fU1olaliW2LLM03l0Uks0sduK3p3tktUQJIIc3bvoVS5wrt1OboCTvnzn1KKdqUJtZ/wSMoy7UYTVYK5wdyh3fd6c25KWE83Ek6sDYYqCSeV3fyAFqFsLQzUnEPpSEeNy4zPaNqWZengxQ7HIIcKeUws6ypvNsVSFUNrfM+152zRFCynWJMumUV3+6r0I8eswl1HTbHneI7Kh+Rm4u+kQIQnx7rAHEcawIx3QEABbyUZV4AzXefglmZbcyDTeaH3i2Ebf7J/JJZoukuIcxlBgLWRh395lLKg6pTUm+VYIBtuxzHjm5ig5Dl++V/6Ae68pp+16CDHMLbVlAydoqgiO9G+jVqdTDNJ8uQ+BdLXqIh270IG1wg7Kpz0w7irMgSjvABD+wt2uDmcO/dzqzv2cgrNNNeQ3HDKVmDvyoUAzOxweU9SSuK++smAhh0lQhWmF/jYIKOo8Z5jyDdV0p8aQP0CdRYR5TxvWi5SlUKu/GBnxRm6X4X1k70+nPUCGpGH4/4DkaHOtcZaxlehItiSjjIf5iVHLVrmUlJ9Zz7xX1UG85/I1aAaFOf3hCXF6aZILpVbw5TSF0ej50px2XWcEpKw0L91FqoNdGLSh5gtuwh4zBPaCHH8Q+BTyoZei+UOZ
  template:
    metadata:
      name: authentik-credentials
      namespace: default
    type: Opaque
