apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kavita
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Blacklotus89898/Homelab.git
    targetRevision: HEAD
    path: services/kavita
  destination:
    server: https://kubernetes.default.svc
    namespace: kavita
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
