apiVersion: v1
kind: LimitRange
metadata:
  name: openobserve-limits
  namespace: openobserve
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 1Gi
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      max:
        cpu: "2"
        memory: 4Gi
