backstage:
  image:
    registry: ghcr.io
    repository: backstage/backstage
    tag: latest
    pullPolicy: Always

  resources:
    requests:
      cpu: 200m
      memory: 768Mi
    limits:
      memory: 2Gi

  appConfig:
    app:
      title: Homelab Portal
      baseUrl: http://192.168.0.108:30900
      extensions:
        - notifications/nav-item:
            disabled: true

    organization:
      name: Homelab

    backend:
      baseUrl: http://192.168.0.108:30900
      listen:
        port: 7007
      database:
        client: pg
        connection:
          host: ${POSTGRES_HOST}
          port: ${POSTGRES_PORT}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
      cors:
        origin: http://192.168.0.108:30900
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      reading:
        allow:
          - host: raw.githubusercontent.com
      csp:
        upgrade-insecure-requests: false

    auth:
      environment: development
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true

    catalog:
      rules:
        - allow: [Component, System, API, Resource, Location]
      locations:
        - type: url
          target: https://raw.githubusercontent.com/Blacklotus89898/Homelab/main/catalog/all.yaml

service:
  type: NodePort
  ports:
    backend: 7007
  nodePorts:
    backend: "30900"

postgresql:
  enabled: true
  auth:
    username: backstage
    password: backstage
    database: backstage
