apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-cleanup
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: git@github.com:Blacklotus89898/Homelab.git
    targetRevision: HEAD
    path: infrastructure/pod-cleanup
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

