apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}-svc
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
spec:
  type: NodePort
  selector:
    app: ${{ values.name }}
  ports:
    - port: ${{ values.containerPort }}
      targetPort: ${{ values.containerPort }}
      nodePort: ${{ values.nodePort }}
      protocol: TCP
