apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd
  description: GitOps continuous deployment
  links:
    - url: http://192.168.0.108:31991
      title: ArgoCD UI
  annotations:
    argocd/app-name: argocd
spec:
  type: service
  lifecycle: production
  owner: user:blacklotus89898
  system: homelab
  providesApis:
    - argocd-api
