apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kavita
  description: Self-hosted manga and comic reader
  links:
    - url: http://192.168.0.108:30050
      title: Kavita UI
  annotations:
    backstage.io/kubernetes-namespace: kavita
    backstage.io/kubernetes-label-selector: 'app=kavita'
    backstage.io/techdocs-ref: url:https://github.com/Blacklotus89898/Homelab/tree/main/services/kavita
  tags:
    - media
    - self-hosted
spec:
  type: service
  lifecycle: production
  owner: user:blacklotus89898
  system: homelab
