apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: linkding
  description: Self-hosted bookmark manager
  links:
    - url: http://192.168.0.108:30090
      title: Linkding UI
  annotations:
    backstage.io/kubernetes-namespace: linkding
    backstage.io/kubernetes-label-selector: 'app=linkding'
    backstage.io/techdocs-ref: url:https://github.com/Blacklotus89898/Homelab/tree/main/services/linkding
  tags:
    - productivity
    - self-hosted
spec:
  type: service
  lifecycle: production
  owner: user:blacklotus89898
  system: homelab
