apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openobserve
  description: Unified logs, metrics, and traces
  links:
    - url: http://192.168.0.108:30500
      title: OpenObserve UI
  annotations:
    argocd/app-name: openobserve
    backstage.io/kubernetes-namespace: openobserve
    backstage.io/kubernetes-label-selector: 'app=openobserve'
spec:
  type: service
  lifecycle: production
  owner: user:blacklotus89898
  system: homelab
  providesApis:
    - openobserve-api
