apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: paperless
  description: Document management system
spec:
  type: service
  lifecycle: production
  owner: user:blacklotus
  system: homelab
